name: ChatControl
main: ${main.class}
version: ${project.version}
author: kangarko
api-version: 1.13
softdepend: [AuthMe, BanManager, CMI, DiscordSRV, Essentials, Factions, Feudal, GriefPrevention, ItemsAdder, LibraryHelper, LegacyFactions, Lands, LiteBans, LuckPerms, mcMMO, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, NashornPlus, Nicky, PartyAndFriends, PlaceholderAPI, ProtocolLib, PvPManager, SimpleClans, Towny, TownyChat, Vault, WorldEdit]
folia-supported: true
# 
# The commands are built at runtime so you can change them easily within the settings.
# Do not change anything in here, you will break the plugin and get no support.
#
commands: 
permissions:
  chatcontrol.receive.announcer: 
    default: true
  chatcontrol.soundnotify:
    default: true
  chatcontrol.chat.read: 
    default: true
  chatcontrol.chat.write: 
    default: true
  chatcontrol.use.color.chat: 
    default: true  
  chatcontrol.use.color.me: 
    default: true  
  chatcontrol.use.color.prefix: 
    default: true  
  chatcontrol.use.color.nick: 
    default: true  
  chatcontrol.use.color.suffix: 
    default: true  
  chatcontrol.use.color.private_message: 
    default: true
  chatcontrol.bypass.spamkick:
    default: true
  chatcontrol.command.toggle.on: 
    default: true
  chatcontrol.command.toggle.off: 
    default: true
  chatcontrol.chat.links:
    default: true
  "chatcontrol.channel.autojoin.*": 
    default: false
  chatcontrol.spy.autoenable:
    default: false
  chatcontrol.bypass.range:
    default: false
  chatcontrol.bypass.range.world: 
    default: false